force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fund__c/fields/Investment_Firm__c.field-meta.xml
<CustomField>
    <fullName>Investment_Firm__c</fullName>
    <label>Investment Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funds</relationshipLabel>
    <relationshipName>Funds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Share_Class__c/Share_Class__c.object-meta.xml
<CustomObject>
    <label>Share Class</label>
    <nameField>
        <label>Share Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Share Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Share_Class__c/fields/Current_Price__c.field-meta.xml
<CustomField>
    <fullName>Current_Price__c</fullName>
    <inlineHelpText>Current Price per unit of the security</inlineHelpText>
    <label>Current Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Share_Class__c/fields/Distribution__c.field-meta.xml
<CustomField>
    <fullName>Distribution__c</fullName>
    <label>Distribution</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Distribution_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Share_Class__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Share Classes</relationshipLabel>
    <relationshipName>Share_Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Share_Class__c/fields/Price_Entered_Date__c.field-meta.xml
<CustomField>
    <fullName>Price_Entered_Date__c</fullName>
    <label>Price Entered Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Share_Class__c/fields/Ticker_Symbol__c.field-meta.xml
<CustomField>
    <fullName>Ticker_Symbol__c</fullName>
    <label>Ticker Symbol</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ShareClassTriggerHelperTest.cls
@isTest
public class ShareClassTriggerHelperTest{
    static testmethod void UpdatePriceEnteredDateTest(){
        Account testAccount = new Account(Name='Test');
        insert testAccount;
        
        Fund__c testFund = new Fund__c(Name='Test Fund', Investment_Firm__c=testAccount.Id);
        insert testFund;

        DateTime testStartTime = DateTime.now().addDays(-1);

        Share_Class__c testShareClass = new Share_Class__c(
            Name='Test Share Class', 
            Fund__c = testFund.Id, 
            Distribution__c = 'Income',
            Current_Price__c = 4.9,
            Price_Entered_Date__c = testStartTime
        );
        insert testShareClass;

        DateTime testTime = DateTime.now();

        testShareClass.Current_Price__c = 5.5;

        List<Share_Class__c> result = ShareClassTriggerHelper.UpdatePriceEnteredDates(new List<Share_Class__c>{testShareClass}, testTime);

        testShareClass = result[0];

        System.assertEquals(testTime, testShareClass.Price_Entered_Date__c);
    }

    static testmethod void DontUpdateIfPriceDoesntChange(){
        Account testAccount = new Account(Name='Test');
        insert testAccount;
        
        Fund__c testFund = new Fund__c(Name='Test Fund', Investment_Firm__c=testAccount.Id);
        insert testFund;

        DateTime testStartTime = DateTime.now().addDays(-1);

        Share_Class__c testShareClass = new Share_Class__c(
            Name='Test Share Class', 
            Fund__c = testFund.Id, 
            Distribution__c = 'Income',
            Current_Price__c = 4.9,
            Price_Entered_Date__c = testStartTime
        );
        insert testShareClass;

        DateTime testTime = DateTime.now();

        testShareClass.Ticker_Symbol__c = 'AV.';

        List<Share_Class__c> result = ShareClassTriggerHelper.UpdatePriceEnteredDates(new List<Share_Class__c>{testShareClass}, testTime);

        testShareClass = result[0];

        System.assertEquals(testStartTime, testShareClass.Price_Entered_Date__c);
    }

    static testmethod void UpdatePriceEnteredDateAutoTest(){
        Account testAccount = new Account(Name='Test');
        insert testAccount;
        
        Fund__c testFund = new Fund__c(Name='Test Fund', Investment_Firm__c=testAccount.Id);
        insert testFund;

        DateTime testStartTime = DateTime.now().addDays(-1);

        Test.startTest();
        Share_Class__c testShareClass = new Share_Class__c(
            Name='Test Share Class', 
            Fund__c = testFund.Id, 
            Distribution__c = 'Income',
            Current_Price__c = 4.9
        );
        insert testShareClass;
        Test.stopTest();

        testShareClass = [select Id, Current_Price__c, Price_Entered_Date__c from Share_Class__c where Id=: testShareClass.Id];

        System.assertNotEquals(null, testShareClass.Price_Entered_Date__c);
    }
}