force-app/main/default/objects/Share_Class__c/Share_Class__c.object-meta.xml
<CustomObject>
    <label>Share Class</label>
    <nameField>
        <label>Share Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Share Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Share_Class__c/fields/Current_Price__c.field-meta.xml
<CustomField>
    <fullName>Current_Price__c</fullName>
    <inlineHelpText>Current Price per unit of the security</inlineHelpText>
    <label>Current Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Share_Class__c/fields/Price_Entered_Date__c.field-meta.xml
<CustomField>
    <fullName>Price_Entered_Date__c</fullName>
    <label>Price Entered Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ShareClassTriggerHelper.cls
public class ShareClassTriggerHelper{
    public static List<Share_Class__c> UpdatePriceEnteredDates(List<Share_Class__c> shareclasses, DateTime timeToSet){
        System.debug('Share Classes');
        System.debug(shareClasses);
        Set<Id> shareClassIds = new Set<Id>();

        for(Share_Class__c shareClass : shareclasses){
            if(shareClass.Id != null){
                shareClassIds.add(shareClass.Id);
            }
        }

        Map<Id, Share_Class__c> oldShareClassesMap = new Map<Id, Share_Class__c>();
        if(!shareClassIds.isEmpty())
        {
            oldShareClassesMap = new Map<Id, Share_Class__c>([select Id, Current_Price__c from Share_Class__c where Id in: shareClassIds]);
        }

        for(Share_Class__c shareClass : shareclasses){
            Share_Class__c oldValue = oldShareClassesMap.get(shareClass.Id);

            //if new or current price changed
            if(oldValue == null || oldValue.Current_Price__c != shareClass.Current_Price__c){
                shareClass.Price_Entered_Date__c = timeToSet;
            }
        }

        return shareclasses;
    }
}