force-app/main/default/objects/Dividend__c/Dividend__c.object-meta.xml
<CustomObject>
    <label>Dividend</label>
    <nameField>
        <displayFormat>DIV-{000000}</displayFormat>
        <label>Dividend Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dividends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dividend__c/fields/Book_Value_at_Dividend__c.field-meta.xml
<CustomField>
    <fullName>Book_Value_at_Dividend__c</fullName>
    <label>Book Value at Dividend</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Dividend__c/fields/Dividend__c.field-meta.xml
<CustomField>
    <fullName>Dividend__c</fullName>
    <label>Dividend</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Dividend__c/fields/Share_Class__c.field-meta.xml
<CustomField>
    <fullName>Share_Class__c</fullName>
    <label>Share Class</label>
    <referenceTo>Share_Class__c</referenceTo>
    <relationshipLabel>Dividends</relationshipLabel>
    <relationshipName>Dividends</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Share_Class__c/Share_Class__c.object-meta.xml
<CustomObject>
    <label>Share Class</label>
    <nameField>
        <label>Share Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Share Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Share_Class__c/fields/Book_Cost__c.field-meta.xml
<CustomField>
    <fullName>Book_Cost__c</fullName>
    <label>Book Cost</label>
    <summarizedField>Transaction__c.Cost__c</summarizedField>
    <summaryForeignKey>Transaction__c.Share_Class__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/TransactionTriggerHelper.cls
public class TransactionTriggerHelper {
    public static void SetBookValueAtDividend(List<Dividend__c> dividends){
        Set<Id> shareClassIds = new Set<Id>();
        
        for(Dividend__c dividend : dividends){
            shareClassIds.add(dividend.Share_Class__c);
        }
        
        Map<Id, Share_Class__c> shareClassMap = new Map<Id, Share_Class__c>([select Id, Book_Cost__c from Share_Class__c where Id in: shareClassIds]);
        
        for(Dividend__c dividend : dividends){
            dividend.Book_Value_at_Dividend__c = shareClassMap.get(dividend.Share_Class__c).Book_Cost__c;
        }
    }
}