force-app/main/default/objects/Dividend__c/Dividend__c.object-meta.xml
<CustomObject>
    <label>Dividend</label>
    <nameField>
        <displayFormat>DIV-{000000}</displayFormat>
        <label>Dividend Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dividends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dividend__c/fields/Book_Value_at_Dividend__c.field-meta.xml
<CustomField>
    <fullName>Book_Value_at_Dividend__c</fullName>
    <label>Book Value at Dividend</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Dividend__c/fields/Dividend__c.field-meta.xml
<CustomField>
    <fullName>Dividend__c</fullName>
    <label>Dividend</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Dividend__c/fields/Share_Class__c.field-meta.xml
<CustomField>
    <fullName>Share_Class__c</fullName>
    <label>Share Class</label>
    <referenceTo>Share_Class__c</referenceTo>
    <relationshipLabel>Dividends</relationshipLabel>
    <relationshipName>Dividends</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fund__c/fields/Investment_Firm__c.field-meta.xml
<CustomField>
    <fullName>Investment_Firm__c</fullName>
    <label>Investment Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Funds</relationshipLabel>
    <relationshipName>Funds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Share_Class__c/Share_Class__c.object-meta.xml
<CustomObject>
    <label>Share Class</label>
    <nameField>
        <label>Share Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Share Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Share_Class__c/fields/Book_Cost__c.field-meta.xml
<CustomField>
    <fullName>Book_Cost__c</fullName>
    <label>Book Cost</label>
    <summarizedField>Transaction__c.Cost__c</summarizedField>
    <summaryForeignKey>Transaction__c.Share_Class__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Share_Class__c/fields/Distribution__c.field-meta.xml
<CustomField>
    <fullName>Distribution__c</fullName>
    <label>Distribution</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Distribution_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Share_Class__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <label>Fund</label>
    <referenceTo>Fund__c</referenceTo>
    <relationshipLabel>Share Classes</relationshipLabel>
    <relationshipName>Share_Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Share_Class__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <label>Units</label>
    <summarizedField>Transaction__c.Units__c</summarizedField>
    <summaryForeignKey>Transaction__c.Share_Class__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRN-{000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Execution_Date__c.field-meta.xml
<CustomField>
    <fullName>Execution_Date__c</fullName>
    <label>Execution Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Settled_Date__c.field-meta.xml
<CustomField>
    <fullName>Settled_Date__c</fullName>
    <label>Settled Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Share_Class__c.field-meta.xml
<CustomField>
    <fullName>Share_Class__c</fullName>
    <label>Share Class</label>
    <referenceTo>Share_Class__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <label>Units</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TransactionTriggerHelperTest.cls
@isTest
public class TransactionTriggerHelperTest {
    static testmethod void CalculateDividendValue(){
        Account testAccount = new Account(Name='Test');
        insert testAccount;
        
        Fund__c testFund = new Fund__c(Name='Test Fund', Investment_Firm__c=testAccount.Id);
        insert testFund;
        
        Share_Class__c testShareClass = new Share_Class__c(Name='Test Share Class', Fund__c = testFund.Id, Distribution__c = 'Income'  );
        insert testShareClass;
        
        Integer randomBookCost = Integer.valueof((Math.random() * 1000))+100;
        
        Transaction__c testTransaction = new Transaction__c(
            Share_Class__c = testShareClass.Id, 
            Settled_Date__c=Date.today().addDays(-1), 
            Cost__c = randomBookCost,
            Units__c = 1,
            Execution_Date__c = Date.today().addDays(-4) 
        );
        insert testTransaction; 
        
        test.startTest();
        testShareClass = [select Id, Book_Cost__c from Share_Class__c where Id=: testShareClass.Id];
        system.assertEquals(randomBookCost , testShareClass.Book_Cost__c);
        
        Dividend__c testDividend = new Dividend__c(Date__c = Date.today(), Share_Class__c = testShareClass.Id, Dividend__c = 10);
        insert testDividend;
        testDividend = [select Id,  Book_Value_at_Dividend__c from Dividend__c where Id=:testDividend.Id];
        
        System.assertEquals(randomBookCost , testDividend.Book_Value_at_Dividend__c);
    }
}